/* eslint-disable */
// WARNING: DO NOT EDIT. This file is automatically generated by AWS Amplify. It will be overwritten.

const awsmobile = {
    "aws_project_region": "eu-west-1",
    "aws_appsync_graphqlEndpoint": "https://7z3nhfs3yrbovdfiscwthumxqq.appsync-api.eu-west-1.amazonaws.com/graphql",
    "aws_appsync_region": "eu-west-1",
    "aws_appsync_authenticationType": "API_KEY",
    "aws_appsync_apiKey": "da2-2uefuabs5rem3hdpemcfnget5i",
    "aws_cloud_logic_custom": [
        {
            "name": "scores",
            "endpoint": "https://1qf9qxbuxj.execute-api.eu-west-1.amazonaws.com/staging",
            "region": "eu-west-1"
        }
    ],
    "aws_cognito_identity_pool_id": "eu-west-1:7eff6161-47b7-43aa-81f6-a4be0c97d0bc",
    "aws_cognito_region": "eu-west-1",
    "aws_user_pools_id": "eu-west-1_mhyhBXzBV",
    "aws_user_pools_web_client_id": "4vku52e7fd6b4b5b0ansaf2ie7",
    "oauth": {
        "domain": "9yc1gyvic50v-staging.auth.eu-west-1.amazoncognito.com",
        "scope": [
            "phone",
            "email",
            "openid",
            "profile",
            "aws.cognito.signin.user.admin"
        ],
        "redirectSignIn": "http://localhost:8081/,http://localhost:8081/",
        "redirectSignOut": "http://localhost:8081/,http://localhost:8081/",
        "responseType": "code"
    },
    "federationTarget": "COGNITO_USER_POOLS",
    "aws_dynamodb_all_tables_region": "eu-west-1",
    "aws_dynamodb_table_schemas": [
        {
            "tableName": "scores-staging",
            "region": "eu-west-1"
        }
    ]
};


export default awsmobile;
